// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0-devel
// 	protoc        v3.12.3
// source: order/orderProto/order.proto

package orderProto

import (
	context "context"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type OrderStruct struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	OrderID    int64               `protobuf:"varint,1,opt,name=OrderID,proto3" json:"OrderID,omitempty"`
	CustomerID int64               `protobuf:"varint,2,opt,name=CustomerID,proto3" json:"CustomerID,omitempty"`
	Restaurant string              `protobuf:"bytes,3,opt,name=Restaurant,proto3" json:"Restaurant,omitempty"`
	ItemLine   []*OrderStruct_Item `protobuf:"bytes,4,rep,name=ItemLine,proto3" json:"ItemLine,omitempty"`
	Price      float32             `protobuf:"fixed32,5,opt,name=Price,proto3" json:"Price,omitempty"`
	Quantity   int64               `protobuf:"varint,6,opt,name=Quantity,proto3" json:"Quantity,omitempty"`
	Discount   int64               `protobuf:"varint,7,opt,name=Discount,proto3" json:"Discount,omitempty"`
	Date       string              `protobuf:"bytes,8,opt,name=Date,proto3" json:"Date,omitempty"`
}

func (x *OrderStruct) Reset() {
	*x = OrderStruct{}
	if protoimpl.UnsafeEnabled {
		mi := &file_order_orderProto_order_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OrderStruct) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderStruct) ProtoMessage() {}

func (x *OrderStruct) ProtoReflect() protoreflect.Message {
	mi := &file_order_orderProto_order_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderStruct.ProtoReflect.Descriptor instead.
func (*OrderStruct) Descriptor() ([]byte, []int) {
	return file_order_orderProto_order_proto_rawDescGZIP(), []int{0}
}

func (x *OrderStruct) GetOrderID() int64 {
	if x != nil {
		return x.OrderID
	}
	return 0
}

func (x *OrderStruct) GetCustomerID() int64 {
	if x != nil {
		return x.CustomerID
	}
	return 0
}

func (x *OrderStruct) GetRestaurant() string {
	if x != nil {
		return x.Restaurant
	}
	return ""
}

func (x *OrderStruct) GetItemLine() []*OrderStruct_Item {
	if x != nil {
		return x.ItemLine
	}
	return nil
}

func (x *OrderStruct) GetPrice() float32 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *OrderStruct) GetQuantity() int64 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

func (x *OrderStruct) GetDiscount() int64 {
	if x != nil {
		return x.Discount
	}
	return 0
}

func (x *OrderStruct) GetDate() string {
	if x != nil {
		return x.Date
	}
	return ""
}

type OrderRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *OrderRequest) Reset() {
	*x = OrderRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_order_orderProto_order_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OrderRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderRequest) ProtoMessage() {}

func (x *OrderRequest) ProtoReflect() protoreflect.Message {
	mi := &file_order_orderProto_order_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderRequest.ProtoReflect.Descriptor instead.
func (*OrderRequest) Descriptor() ([]byte, []int) {
	return file_order_orderProto_order_proto_rawDescGZIP(), []int{1}
}

type OrderResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	OrdRes []*OrderStruct `protobuf:"bytes,1,rep,name=ordRes,proto3" json:"ordRes,omitempty"`
}

func (x *OrderResponse) Reset() {
	*x = OrderResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_order_orderProto_order_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OrderResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderResponse) ProtoMessage() {}

func (x *OrderResponse) ProtoReflect() protoreflect.Message {
	mi := &file_order_orderProto_order_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderResponse.ProtoReflect.Descriptor instead.
func (*OrderResponse) Descriptor() ([]byte, []int) {
	return file_order_orderProto_order_proto_rawDescGZIP(), []int{2}
}

func (x *OrderResponse) GetOrdRes() []*OrderStruct {
	if x != nil {
		return x.OrdRes
	}
	return nil
}

type AvgPriceInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CustomerID int64   `protobuf:"varint,1,opt,name=CustomerID,proto3" json:"CustomerID,omitempty"`
	AvgPrice   float32 `protobuf:"fixed32,2,opt,name=AvgPrice,proto3" json:"AvgPrice,omitempty"`
	AvgOrders  int64   `protobuf:"varint,3,opt,name=AvgOrders,proto3" json:"AvgOrders,omitempty"`
}

func (x *AvgPriceInfo) Reset() {
	*x = AvgPriceInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_order_orderProto_order_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AvgPriceInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AvgPriceInfo) ProtoMessage() {}

func (x *AvgPriceInfo) ProtoReflect() protoreflect.Message {
	mi := &file_order_orderProto_order_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AvgPriceInfo.ProtoReflect.Descriptor instead.
func (*AvgPriceInfo) Descriptor() ([]byte, []int) {
	return file_order_orderProto_order_proto_rawDescGZIP(), []int{3}
}

func (x *AvgPriceInfo) GetCustomerID() int64 {
	if x != nil {
		return x.CustomerID
	}
	return 0
}

func (x *AvgPriceInfo) GetAvgPrice() float32 {
	if x != nil {
		return x.AvgPrice
	}
	return 0
}

func (x *AvgPriceInfo) GetAvgOrders() int64 {
	if x != nil {
		return x.AvgOrders
	}
	return 0
}

type AvgPriceInfoRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *AvgPriceInfoRequest) Reset() {
	*x = AvgPriceInfoRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_order_orderProto_order_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AvgPriceInfoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AvgPriceInfoRequest) ProtoMessage() {}

func (x *AvgPriceInfoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_order_orderProto_order_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AvgPriceInfoRequest.ProtoReflect.Descriptor instead.
func (*AvgPriceInfoRequest) Descriptor() ([]byte, []int) {
	return file_order_orderProto_order_proto_rawDescGZIP(), []int{4}
}

type AvgPriceInfoResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Res []*AvgPriceInfo `protobuf:"bytes,1,rep,name=res,proto3" json:"res,omitempty"`
}

func (x *AvgPriceInfoResponse) Reset() {
	*x = AvgPriceInfoResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_order_orderProto_order_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AvgPriceInfoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AvgPriceInfoResponse) ProtoMessage() {}

func (x *AvgPriceInfoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_order_orderProto_order_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AvgPriceInfoResponse.ProtoReflect.Descriptor instead.
func (*AvgPriceInfoResponse) Descriptor() ([]byte, []int) {
	return file_order_orderProto_order_proto_rawDescGZIP(), []int{5}
}

func (x *AvgPriceInfoResponse) GetRes() []*AvgPriceInfo {
	if x != nil {
		return x.Res
	}
	return nil
}

type TopCustomer struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CustomerID  string  `protobuf:"bytes,1,opt,name=CustomerID,proto3" json:"CustomerID,omitempty"`
	Expenditure float32 `protobuf:"fixed32,2,opt,name=Expenditure,proto3" json:"Expenditure,omitempty"`
}

func (x *TopCustomer) Reset() {
	*x = TopCustomer{}
	if protoimpl.UnsafeEnabled {
		mi := &file_order_orderProto_order_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TopCustomer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TopCustomer) ProtoMessage() {}

func (x *TopCustomer) ProtoReflect() protoreflect.Message {
	mi := &file_order_orderProto_order_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TopCustomer.ProtoReflect.Descriptor instead.
func (*TopCustomer) Descriptor() ([]byte, []int) {
	return file_order_orderProto_order_proto_rawDescGZIP(), []int{6}
}

func (x *TopCustomer) GetCustomerID() string {
	if x != nil {
		return x.CustomerID
	}
	return ""
}

func (x *TopCustomer) GetExpenditure() float32 {
	if x != nil {
		return x.Expenditure
	}
	return 0
}

type TopCustomersRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Num int64 `protobuf:"varint,1,opt,name=Num,proto3" json:"Num,omitempty"`
}

func (x *TopCustomersRequest) Reset() {
	*x = TopCustomersRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_order_orderProto_order_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TopCustomersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TopCustomersRequest) ProtoMessage() {}

func (x *TopCustomersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_order_orderProto_order_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TopCustomersRequest.ProtoReflect.Descriptor instead.
func (*TopCustomersRequest) Descriptor() ([]byte, []int) {
	return file_order_orderProto_order_proto_rawDescGZIP(), []int{7}
}

func (x *TopCustomersRequest) GetNum() int64 {
	if x != nil {
		return x.Num
	}
	return 0
}

type TopCustomersResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Res []*TopCustomer `protobuf:"bytes,1,rep,name=res,proto3" json:"res,omitempty"`
}

func (x *TopCustomersResponse) Reset() {
	*x = TopCustomersResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_order_orderProto_order_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TopCustomersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TopCustomersResponse) ProtoMessage() {}

func (x *TopCustomersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_order_orderProto_order_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TopCustomersResponse.ProtoReflect.Descriptor instead.
func (*TopCustomersResponse) Descriptor() ([]byte, []int) {
	return file_order_orderProto_order_proto_rawDescGZIP(), []int{8}
}

func (x *TopCustomersResponse) GetRes() []*TopCustomer {
	if x != nil {
		return x.Res
	}
	return nil
}

type TopRest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Restaurant string  `protobuf:"bytes,1,opt,name=Restaurant,proto3" json:"Restaurant,omitempty"`
	Revenue    float32 `protobuf:"fixed32,2,opt,name=Revenue,proto3" json:"Revenue,omitempty"`
}

func (x *TopRest) Reset() {
	*x = TopRest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_order_orderProto_order_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TopRest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TopRest) ProtoMessage() {}

func (x *TopRest) ProtoReflect() protoreflect.Message {
	mi := &file_order_orderProto_order_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TopRest.ProtoReflect.Descriptor instead.
func (*TopRest) Descriptor() ([]byte, []int) {
	return file_order_orderProto_order_proto_rawDescGZIP(), []int{9}
}

func (x *TopRest) GetRestaurant() string {
	if x != nil {
		return x.Restaurant
	}
	return ""
}

func (x *TopRest) GetRevenue() float32 {
	if x != nil {
		return x.Revenue
	}
	return 0
}

type TopRestaurantsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Num int64 `protobuf:"varint,1,opt,name=Num,proto3" json:"Num,omitempty"`
}

func (x *TopRestaurantsRequest) Reset() {
	*x = TopRestaurantsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_order_orderProto_order_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TopRestaurantsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TopRestaurantsRequest) ProtoMessage() {}

func (x *TopRestaurantsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_order_orderProto_order_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TopRestaurantsRequest.ProtoReflect.Descriptor instead.
func (*TopRestaurantsRequest) Descriptor() ([]byte, []int) {
	return file_order_orderProto_order_proto_rawDescGZIP(), []int{10}
}

func (x *TopRestaurantsRequest) GetNum() int64 {
	if x != nil {
		return x.Num
	}
	return 0
}

type TopRestaurantsResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Res []*TopRest `protobuf:"bytes,1,rep,name=res,proto3" json:"res,omitempty"`
}

func (x *TopRestaurantsResponse) Reset() {
	*x = TopRestaurantsResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_order_orderProto_order_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TopRestaurantsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TopRestaurantsResponse) ProtoMessage() {}

func (x *TopRestaurantsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_order_orderProto_order_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TopRestaurantsResponse.ProtoReflect.Descriptor instead.
func (*TopRestaurantsResponse) Descriptor() ([]byte, []int) {
	return file_order_orderProto_order_proto_rawDescGZIP(), []int{11}
}

func (x *TopRestaurantsResponse) GetRes() []*TopRest {
	if x != nil {
		return x.Res
	}
	return nil
}

type PostRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Res *OrderStruct `protobuf:"bytes,1,opt,name=res,proto3" json:"res,omitempty"`
}

func (x *PostRequest) Reset() {
	*x = PostRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_order_orderProto_order_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PostRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PostRequest) ProtoMessage() {}

func (x *PostRequest) ProtoReflect() protoreflect.Message {
	mi := &file_order_orderProto_order_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PostRequest.ProtoReflect.Descriptor instead.
func (*PostRequest) Descriptor() ([]byte, []int) {
	return file_order_orderProto_order_proto_rawDescGZIP(), []int{12}
}

func (x *PostRequest) GetRes() *OrderStruct {
	if x != nil {
		return x.Res
	}
	return nil
}

type PostResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Res *OrderStruct `protobuf:"bytes,1,opt,name=res,proto3" json:"res,omitempty"`
}

func (x *PostResponse) Reset() {
	*x = PostResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_order_orderProto_order_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PostResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PostResponse) ProtoMessage() {}

func (x *PostResponse) ProtoReflect() protoreflect.Message {
	mi := &file_order_orderProto_order_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PostResponse.ProtoReflect.Descriptor instead.
func (*PostResponse) Descriptor() ([]byte, []int) {
	return file_order_orderProto_order_proto_rawDescGZIP(), []int{13}
}

func (x *PostResponse) GetRes() *OrderStruct {
	if x != nil {
		return x.Res
	}
	return nil
}

type OrderFilter struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Keyword string `protobuf:"bytes,1,opt,name=keyword,proto3" json:"keyword,omitempty"`
}

func (x *OrderFilter) Reset() {
	*x = OrderFilter{}
	if protoimpl.UnsafeEnabled {
		mi := &file_order_orderProto_order_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OrderFilter) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderFilter) ProtoMessage() {}

func (x *OrderFilter) ProtoReflect() protoreflect.Message {
	mi := &file_order_orderProto_order_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderFilter.ProtoReflect.Descriptor instead.
func (*OrderFilter) Descriptor() ([]byte, []int) {
	return file_order_orderProto_order_proto_rawDescGZIP(), []int{14}
}

func (x *OrderFilter) GetKeyword() string {
	if x != nil {
		return x.Keyword
	}
	return ""
}

type OrderStruct_Item struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name     string  `protobuf:"bytes,1,opt,name=Name,proto3" json:"Name,omitempty"`
	Price    float32 `protobuf:"fixed32,2,opt,name=Price,proto3" json:"Price,omitempty"`
	Quantity int64   `protobuf:"varint,3,opt,name=Quantity,proto3" json:"Quantity,omitempty"`
}

func (x *OrderStruct_Item) Reset() {
	*x = OrderStruct_Item{}
	if protoimpl.UnsafeEnabled {
		mi := &file_order_orderProto_order_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OrderStruct_Item) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderStruct_Item) ProtoMessage() {}

func (x *OrderStruct_Item) ProtoReflect() protoreflect.Message {
	mi := &file_order_orderProto_order_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderStruct_Item.ProtoReflect.Descriptor instead.
func (*OrderStruct_Item) Descriptor() ([]byte, []int) {
	return file_order_orderProto_order_proto_rawDescGZIP(), []int{0, 0}
}

func (x *OrderStruct_Item) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *OrderStruct_Item) GetPrice() float32 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *OrderStruct_Item) GetQuantity() int64 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

var File_order_orderProto_order_proto protoreflect.FileDescriptor

var file_order_orderProto_order_proto_rawDesc = []byte{
	0x0a, 0x1c, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x2f, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x50, 0x72, 0x6f,
	0x74, 0x6f, 0x2f, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x05,
	0x6f, 0x72, 0x64, 0x65, 0x72, 0x22, 0xcc, 0x02, 0x0a, 0x0b, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x53,
	0x74, 0x72, 0x75, 0x63, 0x74, 0x12, 0x18, 0x0a, 0x07, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x49, 0x44,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x07, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x49, 0x44, 0x12,
	0x1e, 0x0a, 0x0a, 0x43, 0x75, 0x73, 0x74, 0x6f, 0x6d, 0x65, 0x72, 0x49, 0x44, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x03, 0x52, 0x0a, 0x43, 0x75, 0x73, 0x74, 0x6f, 0x6d, 0x65, 0x72, 0x49, 0x44, 0x12,
	0x1e, 0x0a, 0x0a, 0x52, 0x65, 0x73, 0x74, 0x61, 0x75, 0x72, 0x61, 0x6e, 0x74, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x0a, 0x52, 0x65, 0x73, 0x74, 0x61, 0x75, 0x72, 0x61, 0x6e, 0x74, 0x12,
	0x33, 0x0a, 0x08, 0x49, 0x74, 0x65, 0x6d, 0x4c, 0x69, 0x6e, 0x65, 0x18, 0x04, 0x20, 0x03, 0x28,
	0x0b, 0x32, 0x17, 0x2e, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x2e, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x53,
	0x74, 0x72, 0x75, 0x63, 0x74, 0x2e, 0x49, 0x74, 0x65, 0x6d, 0x52, 0x08, 0x49, 0x74, 0x65, 0x6d,
	0x4c, 0x69, 0x6e, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x50, 0x72, 0x69, 0x63, 0x65, 0x18, 0x05, 0x20,
	0x01, 0x28, 0x02, 0x52, 0x05, 0x50, 0x72, 0x69, 0x63, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x51, 0x75,
	0x61, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x18, 0x06, 0x20, 0x01, 0x28, 0x03, 0x52, 0x08, 0x51, 0x75,
	0x61, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x12, 0x1a, 0x0a, 0x08, 0x44, 0x69, 0x73, 0x63, 0x6f, 0x75,
	0x6e, 0x74, 0x18, 0x07, 0x20, 0x01, 0x28, 0x03, 0x52, 0x08, 0x44, 0x69, 0x73, 0x63, 0x6f, 0x75,
	0x6e, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x44, 0x61, 0x74, 0x65, 0x18, 0x08, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x04, 0x44, 0x61, 0x74, 0x65, 0x1a, 0x4c, 0x0a, 0x04, 0x49, 0x74, 0x65, 0x6d, 0x12, 0x12,
	0x0a, 0x04, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x4e, 0x61,
	0x6d, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x50, 0x72, 0x69, 0x63, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x02, 0x52, 0x05, 0x50, 0x72, 0x69, 0x63, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x51, 0x75, 0x61, 0x6e,
	0x74, 0x69, 0x74, 0x79, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x08, 0x51, 0x75, 0x61, 0x6e,
	0x74, 0x69, 0x74, 0x79, 0x22, 0x0e, 0x0a, 0x0c, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x22, 0x3b, 0x0a, 0x0d, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x2a, 0x0a, 0x06, 0x6f, 0x72, 0x64, 0x52, 0x65, 0x73, 0x18,
	0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x12, 0x2e, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x2e, 0x4f, 0x72,
	0x64, 0x65, 0x72, 0x53, 0x74, 0x72, 0x75, 0x63, 0x74, 0x52, 0x06, 0x6f, 0x72, 0x64, 0x52, 0x65,
	0x73, 0x22, 0x68, 0x0a, 0x0c, 0x41, 0x76, 0x67, 0x50, 0x72, 0x69, 0x63, 0x65, 0x49, 0x6e, 0x66,
	0x6f, 0x12, 0x1e, 0x0a, 0x0a, 0x43, 0x75, 0x73, 0x74, 0x6f, 0x6d, 0x65, 0x72, 0x49, 0x44, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0a, 0x43, 0x75, 0x73, 0x74, 0x6f, 0x6d, 0x65, 0x72, 0x49,
	0x44, 0x12, 0x1a, 0x0a, 0x08, 0x41, 0x76, 0x67, 0x50, 0x72, 0x69, 0x63, 0x65, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x02, 0x52, 0x08, 0x41, 0x76, 0x67, 0x50, 0x72, 0x69, 0x63, 0x65, 0x12, 0x1c, 0x0a,
	0x09, 0x41, 0x76, 0x67, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x73, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03,
	0x52, 0x09, 0x41, 0x76, 0x67, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x73, 0x22, 0x15, 0x0a, 0x13, 0x41,
	0x76, 0x67, 0x50, 0x72, 0x69, 0x63, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x22, 0x3d, 0x0a, 0x14, 0x41, 0x76, 0x67, 0x50, 0x72, 0x69, 0x63, 0x65, 0x49, 0x6e,
	0x66, 0x6f, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x25, 0x0a, 0x03, 0x72, 0x65,
	0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x13, 0x2e, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x2e,
	0x41, 0x76, 0x67, 0x50, 0x72, 0x69, 0x63, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x03, 0x72, 0x65,
	0x73, 0x22, 0x4f, 0x0a, 0x0b, 0x54, 0x6f, 0x70, 0x43, 0x75, 0x73, 0x74, 0x6f, 0x6d, 0x65, 0x72,
	0x12, 0x1e, 0x0a, 0x0a, 0x43, 0x75, 0x73, 0x74, 0x6f, 0x6d, 0x65, 0x72, 0x49, 0x44, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x43, 0x75, 0x73, 0x74, 0x6f, 0x6d, 0x65, 0x72, 0x49, 0x44,
	0x12, 0x20, 0x0a, 0x0b, 0x45, 0x78, 0x70, 0x65, 0x6e, 0x64, 0x69, 0x74, 0x75, 0x72, 0x65, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x02, 0x52, 0x0b, 0x45, 0x78, 0x70, 0x65, 0x6e, 0x64, 0x69, 0x74, 0x75,
	0x72, 0x65, 0x22, 0x27, 0x0a, 0x13, 0x54, 0x6f, 0x70, 0x43, 0x75, 0x73, 0x74, 0x6f, 0x6d, 0x65,
	0x72, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x10, 0x0a, 0x03, 0x4e, 0x75, 0x6d,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x03, 0x4e, 0x75, 0x6d, 0x22, 0x3c, 0x0a, 0x14, 0x54,
	0x6f, 0x70, 0x43, 0x75, 0x73, 0x74, 0x6f, 0x6d, 0x65, 0x72, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x12, 0x24, 0x0a, 0x03, 0x72, 0x65, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b,
	0x32, 0x12, 0x2e, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x2e, 0x54, 0x6f, 0x70, 0x43, 0x75, 0x73, 0x74,
	0x6f, 0x6d, 0x65, 0x72, 0x52, 0x03, 0x72, 0x65, 0x73, 0x22, 0x43, 0x0a, 0x07, 0x54, 0x6f, 0x70,
	0x52, 0x65, 0x73, 0x74, 0x12, 0x1e, 0x0a, 0x0a, 0x52, 0x65, 0x73, 0x74, 0x61, 0x75, 0x72, 0x61,
	0x6e, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x52, 0x65, 0x73, 0x74, 0x61, 0x75,
	0x72, 0x61, 0x6e, 0x74, 0x12, 0x18, 0x0a, 0x07, 0x52, 0x65, 0x76, 0x65, 0x6e, 0x75, 0x65, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x02, 0x52, 0x07, 0x52, 0x65, 0x76, 0x65, 0x6e, 0x75, 0x65, 0x22, 0x29,
	0x0a, 0x15, 0x54, 0x6f, 0x70, 0x52, 0x65, 0x73, 0x74, 0x61, 0x75, 0x72, 0x61, 0x6e, 0x74, 0x73,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x10, 0x0a, 0x03, 0x4e, 0x75, 0x6d, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x03, 0x52, 0x03, 0x4e, 0x75, 0x6d, 0x22, 0x3a, 0x0a, 0x16, 0x54, 0x6f, 0x70,
	0x52, 0x65, 0x73, 0x74, 0x61, 0x75, 0x72, 0x61, 0x6e, 0x74, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x12, 0x20, 0x0a, 0x03, 0x72, 0x65, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b,
	0x32, 0x0e, 0x2e, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x2e, 0x54, 0x6f, 0x70, 0x52, 0x65, 0x73, 0x74,
	0x52, 0x03, 0x72, 0x65, 0x73, 0x22, 0x33, 0x0a, 0x0b, 0x50, 0x6f, 0x73, 0x74, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x12, 0x24, 0x0a, 0x03, 0x72, 0x65, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x12, 0x2e, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x2e, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x53,
	0x74, 0x72, 0x75, 0x63, 0x74, 0x52, 0x03, 0x72, 0x65, 0x73, 0x22, 0x34, 0x0a, 0x0c, 0x50, 0x6f,
	0x73, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x24, 0x0a, 0x03, 0x72, 0x65,
	0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x12, 0x2e, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x2e,
	0x4f, 0x72, 0x64, 0x65, 0x72, 0x53, 0x74, 0x72, 0x75, 0x63, 0x74, 0x52, 0x03, 0x72, 0x65, 0x73,
	0x22, 0x27, 0x0a, 0x0b, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x46, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x12,
	0x18, 0x0a, 0x07, 0x6b, 0x65, 0x79, 0x77, 0x6f, 0x72, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x07, 0x6b, 0x65, 0x79, 0x77, 0x6f, 0x72, 0x64, 0x32, 0xe7, 0x02, 0x0a, 0x05, 0x4f, 0x72,
	0x64, 0x65, 0x72, 0x12, 0x3a, 0x0a, 0x0b, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x4f, 0x72, 0x64,
	0x65, 0x72, 0x12, 0x13, 0x2e, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x2e, 0x4f, 0x72, 0x64, 0x65, 0x72,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x14, 0x2e, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x2e,
	0x4f, 0x72, 0x64, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12,
	0x4f, 0x0a, 0x12, 0x47, 0x65, 0x74, 0x41, 0x76, 0x67, 0x50, 0x72, 0x69, 0x63, 0x65, 0x73, 0x4f,
	0x72, 0x64, 0x65, 0x72, 0x73, 0x12, 0x1a, 0x2e, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x2e, 0x41, 0x76,
	0x67, 0x50, 0x72, 0x69, 0x63, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x1a, 0x1b, 0x2e, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x2e, 0x41, 0x76, 0x67, 0x50, 0x72, 0x69,
	0x63, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00,
	0x12, 0x4c, 0x0a, 0x0f, 0x47, 0x65, 0x74, 0x54, 0x6f, 0x70, 0x43, 0x75, 0x73, 0x74, 0x6f, 0x6d,
	0x65, 0x72, 0x73, 0x12, 0x1a, 0x2e, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x2e, 0x54, 0x6f, 0x70, 0x43,
	0x75, 0x73, 0x74, 0x6f, 0x6d, 0x65, 0x72, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a,
	0x1b, 0x2e, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x2e, 0x54, 0x6f, 0x70, 0x43, 0x75, 0x73, 0x74, 0x6f,
	0x6d, 0x65, 0x72, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x4b,
	0x0a, 0x0a, 0x47, 0x65, 0x74, 0x54, 0x6f, 0x70, 0x52, 0x65, 0x73, 0x74, 0x12, 0x1c, 0x2e, 0x6f,
	0x72, 0x64, 0x65, 0x72, 0x2e, 0x54, 0x6f, 0x70, 0x52, 0x65, 0x73, 0x74, 0x61, 0x75, 0x72, 0x61,
	0x6e, 0x74, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1d, 0x2e, 0x6f, 0x72, 0x64,
	0x65, 0x72, 0x2e, 0x54, 0x6f, 0x70, 0x52, 0x65, 0x73, 0x74, 0x61, 0x75, 0x72, 0x61, 0x6e, 0x74,
	0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x36, 0x0a, 0x09, 0x50,
	0x6f, 0x73, 0x74, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x12, 0x12, 0x2e, 0x6f, 0x72, 0x64, 0x65, 0x72,
	0x2e, 0x50, 0x6f, 0x73, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x13, 0x2e, 0x6f,
	0x72, 0x64, 0x65, 0x72, 0x2e, 0x50, 0x6f, 0x73, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x22, 0x00, 0x42, 0x12, 0x5a, 0x10, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x2f, 0x6f, 0x72, 0x64,
	0x65, 0x72, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_order_orderProto_order_proto_rawDescOnce sync.Once
	file_order_orderProto_order_proto_rawDescData = file_order_orderProto_order_proto_rawDesc
)

func file_order_orderProto_order_proto_rawDescGZIP() []byte {
	file_order_orderProto_order_proto_rawDescOnce.Do(func() {
		file_order_orderProto_order_proto_rawDescData = protoimpl.X.CompressGZIP(file_order_orderProto_order_proto_rawDescData)
	})
	return file_order_orderProto_order_proto_rawDescData
}

var file_order_orderProto_order_proto_msgTypes = make([]protoimpl.MessageInfo, 16)
var file_order_orderProto_order_proto_goTypes = []interface{}{
	(*OrderStruct)(nil),            // 0: order.OrderStruct
	(*OrderRequest)(nil),           // 1: order.OrderRequest
	(*OrderResponse)(nil),          // 2: order.OrderResponse
	(*AvgPriceInfo)(nil),           // 3: order.AvgPriceInfo
	(*AvgPriceInfoRequest)(nil),    // 4: order.AvgPriceInfoRequest
	(*AvgPriceInfoResponse)(nil),   // 5: order.AvgPriceInfoResponse
	(*TopCustomer)(nil),            // 6: order.TopCustomer
	(*TopCustomersRequest)(nil),    // 7: order.TopCustomersRequest
	(*TopCustomersResponse)(nil),   // 8: order.TopCustomersResponse
	(*TopRest)(nil),                // 9: order.TopRest
	(*TopRestaurantsRequest)(nil),  // 10: order.TopRestaurantsRequest
	(*TopRestaurantsResponse)(nil), // 11: order.TopRestaurantsResponse
	(*PostRequest)(nil),            // 12: order.PostRequest
	(*PostResponse)(nil),           // 13: order.PostResponse
	(*OrderFilter)(nil),            // 14: order.OrderFilter
	(*OrderStruct_Item)(nil),       // 15: order.OrderStruct.Item
}
var file_order_orderProto_order_proto_depIdxs = []int32{
	15, // 0: order.OrderStruct.ItemLine:type_name -> order.OrderStruct.Item
	0,  // 1: order.OrderResponse.ordRes:type_name -> order.OrderStruct
	3,  // 2: order.AvgPriceInfoResponse.res:type_name -> order.AvgPriceInfo
	6,  // 3: order.TopCustomersResponse.res:type_name -> order.TopCustomer
	9,  // 4: order.TopRestaurantsResponse.res:type_name -> order.TopRest
	0,  // 5: order.PostRequest.res:type_name -> order.OrderStruct
	0,  // 6: order.PostResponse.res:type_name -> order.OrderStruct
	1,  // 7: order.Order.CreateOrder:input_type -> order.OrderRequest
	4,  // 8: order.Order.GetAvgPricesOrders:input_type -> order.AvgPriceInfoRequest
	7,  // 9: order.Order.GetTopCustomers:input_type -> order.TopCustomersRequest
	10, // 10: order.Order.GetTopRest:input_type -> order.TopRestaurantsRequest
	12, // 11: order.Order.PostOrder:input_type -> order.PostRequest
	2,  // 12: order.Order.CreateOrder:output_type -> order.OrderResponse
	5,  // 13: order.Order.GetAvgPricesOrders:output_type -> order.AvgPriceInfoResponse
	8,  // 14: order.Order.GetTopCustomers:output_type -> order.TopCustomersResponse
	11, // 15: order.Order.GetTopRest:output_type -> order.TopRestaurantsResponse
	13, // 16: order.Order.PostOrder:output_type -> order.PostResponse
	12, // [12:17] is the sub-list for method output_type
	7,  // [7:12] is the sub-list for method input_type
	7,  // [7:7] is the sub-list for extension type_name
	7,  // [7:7] is the sub-list for extension extendee
	0,  // [0:7] is the sub-list for field type_name
}

func init() { file_order_orderProto_order_proto_init() }
func file_order_orderProto_order_proto_init() {
	if File_order_orderProto_order_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_order_orderProto_order_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*OrderStruct); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_order_orderProto_order_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*OrderRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_order_orderProto_order_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*OrderResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_order_orderProto_order_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AvgPriceInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_order_orderProto_order_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AvgPriceInfoRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_order_orderProto_order_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AvgPriceInfoResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_order_orderProto_order_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TopCustomer); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_order_orderProto_order_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TopCustomersRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_order_orderProto_order_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TopCustomersResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_order_orderProto_order_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TopRest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_order_orderProto_order_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TopRestaurantsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_order_orderProto_order_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TopRestaurantsResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_order_orderProto_order_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PostRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_order_orderProto_order_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PostResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_order_orderProto_order_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*OrderFilter); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_order_orderProto_order_proto_msgTypes[15].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*OrderStruct_Item); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_order_orderProto_order_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   16,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_order_orderProto_order_proto_goTypes,
		DependencyIndexes: file_order_orderProto_order_proto_depIdxs,
		MessageInfos:      file_order_orderProto_order_proto_msgTypes,
	}.Build()
	File_order_orderProto_order_proto = out.File
	file_order_orderProto_order_proto_rawDesc = nil
	file_order_orderProto_order_proto_goTypes = nil
	file_order_orderProto_order_proto_depIdxs = nil
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// OrderClient is the client API for Order service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type OrderClient interface {
	CreateOrder(ctx context.Context, in *OrderRequest, opts ...grpc.CallOption) (*OrderResponse, error)
	GetAvgPricesOrders(ctx context.Context, in *AvgPriceInfoRequest, opts ...grpc.CallOption) (*AvgPriceInfoResponse, error)
	GetTopCustomers(ctx context.Context, in *TopCustomersRequest, opts ...grpc.CallOption) (*TopCustomersResponse, error)
	GetTopRest(ctx context.Context, in *TopRestaurantsRequest, opts ...grpc.CallOption) (*TopRestaurantsResponse, error)
	PostOrder(ctx context.Context, in *PostRequest, opts ...grpc.CallOption) (*PostResponse, error)
}

type orderClient struct {
	cc grpc.ClientConnInterface
}

func NewOrderClient(cc grpc.ClientConnInterface) OrderClient {
	return &orderClient{cc}
}

func (c *orderClient) CreateOrder(ctx context.Context, in *OrderRequest, opts ...grpc.CallOption) (*OrderResponse, error) {
	out := new(OrderResponse)
	err := c.cc.Invoke(ctx, "/order.Order/CreateOrder", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *orderClient) GetAvgPricesOrders(ctx context.Context, in *AvgPriceInfoRequest, opts ...grpc.CallOption) (*AvgPriceInfoResponse, error) {
	out := new(AvgPriceInfoResponse)
	err := c.cc.Invoke(ctx, "/order.Order/GetAvgPricesOrders", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *orderClient) GetTopCustomers(ctx context.Context, in *TopCustomersRequest, opts ...grpc.CallOption) (*TopCustomersResponse, error) {
	out := new(TopCustomersResponse)
	err := c.cc.Invoke(ctx, "/order.Order/GetTopCustomers", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *orderClient) GetTopRest(ctx context.Context, in *TopRestaurantsRequest, opts ...grpc.CallOption) (*TopRestaurantsResponse, error) {
	out := new(TopRestaurantsResponse)
	err := c.cc.Invoke(ctx, "/order.Order/GetTopRest", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *orderClient) PostOrder(ctx context.Context, in *PostRequest, opts ...grpc.CallOption) (*PostResponse, error) {
	out := new(PostResponse)
	err := c.cc.Invoke(ctx, "/order.Order/PostOrder", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// OrderServer is the server API for Order service.
type OrderServer interface {
	CreateOrder(context.Context, *OrderRequest) (*OrderResponse, error)
	GetAvgPricesOrders(context.Context, *AvgPriceInfoRequest) (*AvgPriceInfoResponse, error)
	GetTopCustomers(context.Context, *TopCustomersRequest) (*TopCustomersResponse, error)
	GetTopRest(context.Context, *TopRestaurantsRequest) (*TopRestaurantsResponse, error)
	PostOrder(context.Context, *PostRequest) (*PostResponse, error)
}

// UnimplementedOrderServer can be embedded to have forward compatible implementations.
type UnimplementedOrderServer struct {
}

func (*UnimplementedOrderServer) CreateOrder(context.Context, *OrderRequest) (*OrderResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateOrder not implemented")
}
func (*UnimplementedOrderServer) GetAvgPricesOrders(context.Context, *AvgPriceInfoRequest) (*AvgPriceInfoResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAvgPricesOrders not implemented")
}
func (*UnimplementedOrderServer) GetTopCustomers(context.Context, *TopCustomersRequest) (*TopCustomersResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetTopCustomers not implemented")
}
func (*UnimplementedOrderServer) GetTopRest(context.Context, *TopRestaurantsRequest) (*TopRestaurantsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetTopRest not implemented")
}
func (*UnimplementedOrderServer) PostOrder(context.Context, *PostRequest) (*PostResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PostOrder not implemented")
}

func RegisterOrderServer(s *grpc.Server, srv OrderServer) {
	s.RegisterService(&_Order_serviceDesc, srv)
}

func _Order_CreateOrder_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(OrderRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrderServer).CreateOrder(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/order.Order/CreateOrder",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrderServer).CreateOrder(ctx, req.(*OrderRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Order_GetAvgPricesOrders_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AvgPriceInfoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrderServer).GetAvgPricesOrders(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/order.Order/GetAvgPricesOrders",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrderServer).GetAvgPricesOrders(ctx, req.(*AvgPriceInfoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Order_GetTopCustomers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TopCustomersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrderServer).GetTopCustomers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/order.Order/GetTopCustomers",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrderServer).GetTopCustomers(ctx, req.(*TopCustomersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Order_GetTopRest_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TopRestaurantsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrderServer).GetTopRest(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/order.Order/GetTopRest",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrderServer).GetTopRest(ctx, req.(*TopRestaurantsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Order_PostOrder_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PostRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrderServer).PostOrder(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/order.Order/PostOrder",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrderServer).PostOrder(ctx, req.(*PostRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Order_serviceDesc = grpc.ServiceDesc{
	ServiceName: "order.Order",
	HandlerType: (*OrderServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateOrder",
			Handler:    _Order_CreateOrder_Handler,
		},
		{
			MethodName: "GetAvgPricesOrders",
			Handler:    _Order_GetAvgPricesOrders_Handler,
		},
		{
			MethodName: "GetTopCustomers",
			Handler:    _Order_GetTopCustomers_Handler,
		},
		{
			MethodName: "GetTopRest",
			Handler:    _Order_GetTopRest_Handler,
		},
		{
			MethodName: "PostOrder",
			Handler:    _Order_PostOrder_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "order/orderProto/order.proto",
}
