// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0-devel
// 	protoc        v3.12.3
// source: src/order/orderProto/order.proto

package orderProto

import (
	context "context"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type OrderRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	OrderID    int64                `protobuf:"varint,1,opt,name=OrderID,proto3" json:"OrderID,omitempty"`
	CustomerID int64                `protobuf:"varint,2,opt,name=CustomerID,proto3" json:"CustomerID,omitempty"`
	Restaurant string               `protobuf:"bytes,3,opt,name=Restaurant,proto3" json:"Restaurant,omitempty"`
	ItemLine   []*OrderRequest_Item `protobuf:"bytes,4,rep,name=ItemLine,proto3" json:"ItemLine,omitempty"`
	Price      float32              `protobuf:"fixed32,5,opt,name=Price,proto3" json:"Price,omitempty"`
	Quantity   int64                `protobuf:"varint,6,opt,name=Quantity,proto3" json:"Quantity,omitempty"`
	Discount   int64                `protobuf:"varint,7,opt,name=Discount,proto3" json:"Discount,omitempty"`
	Date       string               `protobuf:"bytes,8,opt,name=Date,proto3" json:"Date,omitempty"`
}

func (x *OrderRequest) Reset() {
	*x = OrderRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_src_order_orderProto_order_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OrderRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderRequest) ProtoMessage() {}

func (x *OrderRequest) ProtoReflect() protoreflect.Message {
	mi := &file_src_order_orderProto_order_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderRequest.ProtoReflect.Descriptor instead.
func (*OrderRequest) Descriptor() ([]byte, []int) {
	return file_src_order_orderProto_order_proto_rawDescGZIP(), []int{0}
}

func (x *OrderRequest) GetOrderID() int64 {
	if x != nil {
		return x.OrderID
	}
	return 0
}

func (x *OrderRequest) GetCustomerID() int64 {
	if x != nil {
		return x.CustomerID
	}
	return 0
}

func (x *OrderRequest) GetRestaurant() string {
	if x != nil {
		return x.Restaurant
	}
	return ""
}

func (x *OrderRequest) GetItemLine() []*OrderRequest_Item {
	if x != nil {
		return x.ItemLine
	}
	return nil
}

func (x *OrderRequest) GetPrice() float32 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *OrderRequest) GetQuantity() int64 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

func (x *OrderRequest) GetDiscount() int64 {
	if x != nil {
		return x.Discount
	}
	return 0
}

func (x *OrderRequest) GetDate() string {
	if x != nil {
		return x.Date
	}
	return ""
}

type AvgPriceInfoRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CustomerID int64   `protobuf:"varint,1,opt,name=CustomerID,proto3" json:"CustomerID,omitempty"`
	AvgPrice   float32 `protobuf:"fixed32,2,opt,name=AvgPrice,proto3" json:"AvgPrice,omitempty"`
	AvgOrders  int64   `protobuf:"varint,3,opt,name=AvgOrders,proto3" json:"AvgOrders,omitempty"`
}

func (x *AvgPriceInfoRequest) Reset() {
	*x = AvgPriceInfoRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_src_order_orderProto_order_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AvgPriceInfoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AvgPriceInfoRequest) ProtoMessage() {}

func (x *AvgPriceInfoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_src_order_orderProto_order_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AvgPriceInfoRequest.ProtoReflect.Descriptor instead.
func (*AvgPriceInfoRequest) Descriptor() ([]byte, []int) {
	return file_src_order_orderProto_order_proto_rawDescGZIP(), []int{1}
}

func (x *AvgPriceInfoRequest) GetCustomerID() int64 {
	if x != nil {
		return x.CustomerID
	}
	return 0
}

func (x *AvgPriceInfoRequest) GetAvgPrice() float32 {
	if x != nil {
		return x.AvgPrice
	}
	return 0
}

func (x *AvgPriceInfoRequest) GetAvgOrders() int64 {
	if x != nil {
		return x.AvgOrders
	}
	return 0
}

type TopCustomersRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CustomerID  string  `protobuf:"bytes,1,opt,name=CustomerID,proto3" json:"CustomerID,omitempty"`
	Expenditure float32 `protobuf:"fixed32,2,opt,name=Expenditure,proto3" json:"Expenditure,omitempty"`
}

func (x *TopCustomersRequest) Reset() {
	*x = TopCustomersRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_src_order_orderProto_order_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TopCustomersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TopCustomersRequest) ProtoMessage() {}

func (x *TopCustomersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_src_order_orderProto_order_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TopCustomersRequest.ProtoReflect.Descriptor instead.
func (*TopCustomersRequest) Descriptor() ([]byte, []int) {
	return file_src_order_orderProto_order_proto_rawDescGZIP(), []int{2}
}

func (x *TopCustomersRequest) GetCustomerID() string {
	if x != nil {
		return x.CustomerID
	}
	return ""
}

func (x *TopCustomersRequest) GetExpenditure() float32 {
	if x != nil {
		return x.Expenditure
	}
	return 0
}

type TopRestaurantsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Restaurant string  `protobuf:"bytes,1,opt,name=Restaurant,proto3" json:"Restaurant,omitempty"`
	Revenue    float32 `protobuf:"fixed32,2,opt,name=Revenue,proto3" json:"Revenue,omitempty"`
}

func (x *TopRestaurantsRequest) Reset() {
	*x = TopRestaurantsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_src_order_orderProto_order_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TopRestaurantsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TopRestaurantsRequest) ProtoMessage() {}

func (x *TopRestaurantsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_src_order_orderProto_order_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TopRestaurantsRequest.ProtoReflect.Descriptor instead.
func (*TopRestaurantsRequest) Descriptor() ([]byte, []int) {
	return file_src_order_orderProto_order_proto_rawDescGZIP(), []int{3}
}

func (x *TopRestaurantsRequest) GetRestaurant() string {
	if x != nil {
		return x.Restaurant
	}
	return ""
}

func (x *TopRestaurantsRequest) GetRevenue() float32 {
	if x != nil {
		return x.Revenue
	}
	return 0
}

type OrderResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id      int64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Success bool  `protobuf:"varint,2,opt,name=success,proto3" json:"success,omitempty"`
}

func (x *OrderResponse) Reset() {
	*x = OrderResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_src_order_orderProto_order_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OrderResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderResponse) ProtoMessage() {}

func (x *OrderResponse) ProtoReflect() protoreflect.Message {
	mi := &file_src_order_orderProto_order_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderResponse.ProtoReflect.Descriptor instead.
func (*OrderResponse) Descriptor() ([]byte, []int) {
	return file_src_order_orderProto_order_proto_rawDescGZIP(), []int{4}
}

func (x *OrderResponse) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *OrderResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type OrderFilter struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Keyword string `protobuf:"bytes,1,opt,name=keyword,proto3" json:"keyword,omitempty"`
}

func (x *OrderFilter) Reset() {
	*x = OrderFilter{}
	if protoimpl.UnsafeEnabled {
		mi := &file_src_order_orderProto_order_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OrderFilter) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderFilter) ProtoMessage() {}

func (x *OrderFilter) ProtoReflect() protoreflect.Message {
	mi := &file_src_order_orderProto_order_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderFilter.ProtoReflect.Descriptor instead.
func (*OrderFilter) Descriptor() ([]byte, []int) {
	return file_src_order_orderProto_order_proto_rawDescGZIP(), []int{5}
}

func (x *OrderFilter) GetKeyword() string {
	if x != nil {
		return x.Keyword
	}
	return ""
}

type OrderRequest_Item struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name     string  `protobuf:"bytes,1,opt,name=Name,proto3" json:"Name,omitempty"`
	Price    float32 `protobuf:"fixed32,2,opt,name=Price,proto3" json:"Price,omitempty"`
	Quantity int64   `protobuf:"varint,3,opt,name=Quantity,proto3" json:"Quantity,omitempty"`
}

func (x *OrderRequest_Item) Reset() {
	*x = OrderRequest_Item{}
	if protoimpl.UnsafeEnabled {
		mi := &file_src_order_orderProto_order_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OrderRequest_Item) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderRequest_Item) ProtoMessage() {}

func (x *OrderRequest_Item) ProtoReflect() protoreflect.Message {
	mi := &file_src_order_orderProto_order_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderRequest_Item.ProtoReflect.Descriptor instead.
func (*OrderRequest_Item) Descriptor() ([]byte, []int) {
	return file_src_order_orderProto_order_proto_rawDescGZIP(), []int{0, 0}
}

func (x *OrderRequest_Item) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *OrderRequest_Item) GetPrice() float32 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *OrderRequest_Item) GetQuantity() int64 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

var File_src_order_orderProto_order_proto protoreflect.FileDescriptor

var file_src_order_orderProto_order_proto_rawDesc = []byte{
	0x0a, 0x20, 0x73, 0x72, 0x63, 0x2f, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x2f, 0x6f, 0x72, 0x64, 0x65,
	0x72, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x12, 0x05, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x22, 0xce, 0x02, 0x0a, 0x0c, 0x4f, 0x72,
	0x64, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x18, 0x0a, 0x07, 0x4f, 0x72,
	0x64, 0x65, 0x72, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x07, 0x4f, 0x72, 0x64,
	0x65, 0x72, 0x49, 0x44, 0x12, 0x1e, 0x0a, 0x0a, 0x43, 0x75, 0x73, 0x74, 0x6f, 0x6d, 0x65, 0x72,
	0x49, 0x44, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0a, 0x43, 0x75, 0x73, 0x74, 0x6f, 0x6d,
	0x65, 0x72, 0x49, 0x44, 0x12, 0x1e, 0x0a, 0x0a, 0x52, 0x65, 0x73, 0x74, 0x61, 0x75, 0x72, 0x61,
	0x6e, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x52, 0x65, 0x73, 0x74, 0x61, 0x75,
	0x72, 0x61, 0x6e, 0x74, 0x12, 0x34, 0x0a, 0x08, 0x49, 0x74, 0x65, 0x6d, 0x4c, 0x69, 0x6e, 0x65,
	0x18, 0x04, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x18, 0x2e, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x2e, 0x4f,
	0x72, 0x64, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x2e, 0x49, 0x74, 0x65, 0x6d,
	0x52, 0x08, 0x49, 0x74, 0x65, 0x6d, 0x4c, 0x69, 0x6e, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x50, 0x72,
	0x69, 0x63, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x02, 0x52, 0x05, 0x50, 0x72, 0x69, 0x63, 0x65,
	0x12, 0x1a, 0x0a, 0x08, 0x51, 0x75, 0x61, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x18, 0x06, 0x20, 0x01,
	0x28, 0x03, 0x52, 0x08, 0x51, 0x75, 0x61, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x12, 0x1a, 0x0a, 0x08,
	0x44, 0x69, 0x73, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x07, 0x20, 0x01, 0x28, 0x03, 0x52, 0x08,
	0x44, 0x69, 0x73, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x44, 0x61, 0x74, 0x65,
	0x18, 0x08, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x44, 0x61, 0x74, 0x65, 0x1a, 0x4c, 0x0a, 0x04,
	0x49, 0x74, 0x65, 0x6d, 0x12, 0x12, 0x0a, 0x04, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x04, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x50, 0x72, 0x69, 0x63,
	0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x02, 0x52, 0x05, 0x50, 0x72, 0x69, 0x63, 0x65, 0x12, 0x1a,
	0x0a, 0x08, 0x51, 0x75, 0x61, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03,
	0x52, 0x08, 0x51, 0x75, 0x61, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x22, 0x6f, 0x0a, 0x13, 0x41, 0x76,
	0x67, 0x50, 0x72, 0x69, 0x63, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x12, 0x1e, 0x0a, 0x0a, 0x43, 0x75, 0x73, 0x74, 0x6f, 0x6d, 0x65, 0x72, 0x49, 0x44, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0a, 0x43, 0x75, 0x73, 0x74, 0x6f, 0x6d, 0x65, 0x72, 0x49,
	0x44, 0x12, 0x1a, 0x0a, 0x08, 0x41, 0x76, 0x67, 0x50, 0x72, 0x69, 0x63, 0x65, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x02, 0x52, 0x08, 0x41, 0x76, 0x67, 0x50, 0x72, 0x69, 0x63, 0x65, 0x12, 0x1c, 0x0a,
	0x09, 0x41, 0x76, 0x67, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x73, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03,
	0x52, 0x09, 0x41, 0x76, 0x67, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x73, 0x22, 0x57, 0x0a, 0x13, 0x54,
	0x6f, 0x70, 0x43, 0x75, 0x73, 0x74, 0x6f, 0x6d, 0x65, 0x72, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x12, 0x1e, 0x0a, 0x0a, 0x43, 0x75, 0x73, 0x74, 0x6f, 0x6d, 0x65, 0x72, 0x49, 0x44,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x43, 0x75, 0x73, 0x74, 0x6f, 0x6d, 0x65, 0x72,
	0x49, 0x44, 0x12, 0x20, 0x0a, 0x0b, 0x45, 0x78, 0x70, 0x65, 0x6e, 0x64, 0x69, 0x74, 0x75, 0x72,
	0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x02, 0x52, 0x0b, 0x45, 0x78, 0x70, 0x65, 0x6e, 0x64, 0x69,
	0x74, 0x75, 0x72, 0x65, 0x22, 0x51, 0x0a, 0x15, 0x54, 0x6f, 0x70, 0x52, 0x65, 0x73, 0x74, 0x61,
	0x75, 0x72, 0x61, 0x6e, 0x74, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1e, 0x0a,
	0x0a, 0x52, 0x65, 0x73, 0x74, 0x61, 0x75, 0x72, 0x61, 0x6e, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x0a, 0x52, 0x65, 0x73, 0x74, 0x61, 0x75, 0x72, 0x61, 0x6e, 0x74, 0x12, 0x18, 0x0a,
	0x07, 0x52, 0x65, 0x76, 0x65, 0x6e, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x02, 0x52, 0x07,
	0x52, 0x65, 0x76, 0x65, 0x6e, 0x75, 0x65, 0x22, 0x39, 0x0a, 0x0d, 0x4f, 0x72, 0x64, 0x65, 0x72,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x03, 0x52, 0x02, 0x69, 0x64, 0x12, 0x18, 0x0a, 0x07, 0x73, 0x75, 0x63, 0x63,
	0x65, 0x73, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x08, 0x52, 0x07, 0x73, 0x75, 0x63, 0x63, 0x65,
	0x73, 0x73, 0x22, 0x27, 0x0a, 0x0b, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x46, 0x69, 0x6c, 0x74, 0x65,
	0x72, 0x12, 0x18, 0x0a, 0x07, 0x6b, 0x65, 0x79, 0x77, 0x6f, 0x72, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x07, 0x6b, 0x65, 0x79, 0x77, 0x6f, 0x72, 0x64, 0x32, 0x7d, 0x0a, 0x05, 0x4f,
	0x72, 0x64, 0x65, 0x72, 0x12, 0x38, 0x0a, 0x09, 0x47, 0x65, 0x74, 0x4f, 0x72, 0x64, 0x65, 0x72,
	0x73, 0x12, 0x12, 0x2e, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x2e, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x46,
	0x69, 0x6c, 0x74, 0x65, 0x72, 0x1a, 0x13, 0x2e, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x2e, 0x4f, 0x72,
	0x64, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x00, 0x30, 0x01, 0x12, 0x3a,
	0x0a, 0x0b, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x12, 0x13, 0x2e,
	0x6f, 0x72, 0x64, 0x65, 0x72, 0x2e, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x1a, 0x14, 0x2e, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x2e, 0x4f, 0x72, 0x64, 0x65, 0x72,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x42, 0x12, 0x5a, 0x10, 0x6f, 0x72,
	0x64, 0x65, 0x72, 0x2f, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_src_order_orderProto_order_proto_rawDescOnce sync.Once
	file_src_order_orderProto_order_proto_rawDescData = file_src_order_orderProto_order_proto_rawDesc
)

func file_src_order_orderProto_order_proto_rawDescGZIP() []byte {
	file_src_order_orderProto_order_proto_rawDescOnce.Do(func() {
		file_src_order_orderProto_order_proto_rawDescData = protoimpl.X.CompressGZIP(file_src_order_orderProto_order_proto_rawDescData)
	})
	return file_src_order_orderProto_order_proto_rawDescData
}

var file_src_order_orderProto_order_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_src_order_orderProto_order_proto_goTypes = []interface{}{
	(*OrderRequest)(nil),          // 0: order.OrderRequest
	(*AvgPriceInfoRequest)(nil),   // 1: order.AvgPriceInfoRequest
	(*TopCustomersRequest)(nil),   // 2: order.TopCustomersRequest
	(*TopRestaurantsRequest)(nil), // 3: order.TopRestaurantsRequest
	(*OrderResponse)(nil),         // 4: order.OrderResponse
	(*OrderFilter)(nil),           // 5: order.OrderFilter
	(*OrderRequest_Item)(nil),     // 6: order.OrderRequest.Item
}
var file_src_order_orderProto_order_proto_depIdxs = []int32{
	6, // 0: order.OrderRequest.ItemLine:type_name -> order.OrderRequest.Item
	5, // 1: order.Order.GetOrders:input_type -> order.OrderFilter
	0, // 2: order.Order.CreateOrder:input_type -> order.OrderRequest
	0, // 3: order.Order.GetOrders:output_type -> order.OrderRequest
	4, // 4: order.Order.CreateOrder:output_type -> order.OrderResponse
	3, // [3:5] is the sub-list for method output_type
	1, // [1:3] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_src_order_orderProto_order_proto_init() }
func file_src_order_orderProto_order_proto_init() {
	if File_src_order_orderProto_order_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_src_order_orderProto_order_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*OrderRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_src_order_orderProto_order_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AvgPriceInfoRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_src_order_orderProto_order_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TopCustomersRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_src_order_orderProto_order_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TopRestaurantsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_src_order_orderProto_order_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*OrderResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_src_order_orderProto_order_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*OrderFilter); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_src_order_orderProto_order_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*OrderRequest_Item); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_src_order_orderProto_order_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_src_order_orderProto_order_proto_goTypes,
		DependencyIndexes: file_src_order_orderProto_order_proto_depIdxs,
		MessageInfos:      file_src_order_orderProto_order_proto_msgTypes,
	}.Build()
	File_src_order_orderProto_order_proto = out.File
	file_src_order_orderProto_order_proto_rawDesc = nil
	file_src_order_orderProto_order_proto_goTypes = nil
	file_src_order_orderProto_order_proto_depIdxs = nil
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// OrderClient is the client API for Order service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type OrderClient interface {
	// Get all Orders with filter - A server-to-client streaming RPC.
	GetOrders(ctx context.Context, in *OrderFilter, opts ...grpc.CallOption) (Order_GetOrdersClient, error)
	// Create a new Customer - A simple RPC
	CreateOrder(ctx context.Context, in *OrderRequest, opts ...grpc.CallOption) (*OrderResponse, error)
}

type orderClient struct {
	cc grpc.ClientConnInterface
}

func NewOrderClient(cc grpc.ClientConnInterface) OrderClient {
	return &orderClient{cc}
}

func (c *orderClient) GetOrders(ctx context.Context, in *OrderFilter, opts ...grpc.CallOption) (Order_GetOrdersClient, error) {
	stream, err := c.cc.NewStream(ctx, &_Order_serviceDesc.Streams[0], "/order.Order/GetOrders", opts...)
	if err != nil {
		return nil, err
	}
	x := &orderGetOrdersClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type Order_GetOrdersClient interface {
	Recv() (*OrderRequest, error)
	grpc.ClientStream
}

type orderGetOrdersClient struct {
	grpc.ClientStream
}

func (x *orderGetOrdersClient) Recv() (*OrderRequest, error) {
	m := new(OrderRequest)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *orderClient) CreateOrder(ctx context.Context, in *OrderRequest, opts ...grpc.CallOption) (*OrderResponse, error) {
	out := new(OrderResponse)
	err := c.cc.Invoke(ctx, "/order.Order/CreateOrder", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// OrderServer is the server API for Order service.
type OrderServer interface {
	// Get all Orders with filter - A server-to-client streaming RPC.
	GetOrders(*OrderFilter, Order_GetOrdersServer) error
	// Create a new Customer - A simple RPC
	CreateOrder(context.Context, *OrderRequest) (*OrderResponse, error)
}

// UnimplementedOrderServer can be embedded to have forward compatible implementations.
type UnimplementedOrderServer struct {
}

func (*UnimplementedOrderServer) GetOrders(*OrderFilter, Order_GetOrdersServer) error {
	return status.Errorf(codes.Unimplemented, "method GetOrders not implemented")
}
func (*UnimplementedOrderServer) CreateOrder(context.Context, *OrderRequest) (*OrderResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateOrder not implemented")
}

func RegisterOrderServer(s *grpc.Server, srv OrderServer) {
	s.RegisterService(&_Order_serviceDesc, srv)
}

func _Order_GetOrders_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(OrderFilter)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(OrderServer).GetOrders(m, &orderGetOrdersServer{stream})
}

type Order_GetOrdersServer interface {
	Send(*OrderRequest) error
	grpc.ServerStream
}

type orderGetOrdersServer struct {
	grpc.ServerStream
}

func (x *orderGetOrdersServer) Send(m *OrderRequest) error {
	return x.ServerStream.SendMsg(m)
}

func _Order_CreateOrder_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(OrderRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrderServer).CreateOrder(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/order.Order/CreateOrder",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrderServer).CreateOrder(ctx, req.(*OrderRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Order_serviceDesc = grpc.ServiceDesc{
	ServiceName: "order.Order",
	HandlerType: (*OrderServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateOrder",
			Handler:    _Order_CreateOrder_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "GetOrders",
			Handler:       _Order_GetOrders_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "src/order/orderProto/order.proto",
}
